module.exports = {
  "rules": {
    "comma-dangle": ['error', 'always-multiline'],
    "no-cond-assign": [2, 'always'],
    "no-constant-condition": 2,
    "no-control-regex": 2,
    "no-debugger": 0,
    "no-dupe-args": 2,
    "no-dupe-keys": 2,
    "no-duplicate-case": 2,
    "no-empty": 2,

    // ex. /^abc[]/
    "no-empty-character-class": 2,
    "no-ex-assign": 2,
    "no-extra-boolean-cast": 2,
    "no-extra-parens": 0,
    "no-extra-semi": 2,
    "no-func-assign": 2,
    "no-inner-declarations": 2,
    "no-invalid-regexp": 2,
    "no-irregular-whitespace": [2, {'skipComments': true}],
    "no-negated-in-lhs": 2,
    "no-obj-calls": 2,
    "no-regex-spaces": 2,
    "no-sparse-arrays": 2,
    "no-unexpected-multiline": 2,
    "no-unreachable": 2,
    "use-isnan": 2,
    "valid-jsdoc": 0,
    "valid-typeof": 2,

    /*
     * Best Practices
     */

    "dot-location": [2, "property"],
    "dot-notation": 2,
    "eqeqeq": 2,
    "no-caller": 2,
    "no-empty-function": 0,
    "no-empty-pattern": 2,
    "no-eq-null": 2,
    "no-eval": 2,
    "no-extend-native": 2,
    "no-extra-bind": 2,
    "no-implied-eval": 2,
    "no-iterator": 2,
    "no-labels": 2,
    "no-lone-blocks": 2,
    "no-loop-func": 2,
    "no-multi-spaces": 0,
    "no-multi-str": 2,
    "no-native-reassign": 2,
    "no-new": 2,
    "no-new-func": 2,
    "no-new-wrappers": 2,
    "no-octal": 2,
    "no-octal-escape": 2,
    "no-proto": 2,
    "no-redeclare": 2,
    "no-script-url": 2,
    "no-self-assign": 2,
    "no-self-compare": 2,
    "no-sequences": 2,
    "no-throw-literal": 2,
    "no-unused-expressions": 0,
    "no-useless-call": 2,
    "no-useless-concat": 2,
    "no-useless-escape": 0,
    "no-void": 2,
    "no-with": 2,

    "no-delete-var": 2,
    "no-shadow": 2,
    "no-unused-vars": 2,
    "no-use-before-define": 0,

    /*
     * Stylistics
     */

    "array-bracket-spacing": 0,
    "block-spacing": [2, "always"],
    "brace-style": [2, "1tbs", {
      "allowSingleLine": true,
    }],
    "camelcase": 0,
    "comma-spacing": 0,
    "comma-style": 2,
    "computed-property-spacing": 2,
    "consistent-this": [2, "that"],
    "indent": [2, 2],
    "jsx-quotes": [2, "prefer-single"],
    "key-spacing": [2, {
      "singleLine": {
        "beforeColon": false,
        "afterColon": true,
      },
      "multiLine": {
        "beforeColon": false,
        "afterColon": true,
        "align": "colon",
      },
    }],
    "no-multiple-empty-lines": 2,
    "no-spaced-func": 2,
    "no-trailing-spaces": 2,
    "no-unneeded-ternary": 2,
    "no-whitespace-before-property": 2,
    "object-curly-spacing": 0,
    "semi": [2, "never"],
  },
}
